import json
import re
from pathlib import Path

base_dir = Path('Test Content/Reading Comprehension ')

q = {
    1: [
        {
            "question": "What operational stance does the crew adopt toward wildfire behavior?",
            "choices": {
                "A": "Assume steady movement",
                "B": "Treat conditions as volatile and monitor continuously",
                "C": "Rely on past fire maps",
                "D": "Wait for humidity to stabilize",
            },
            "answer": "B",
            "explanation": "They regard small weather shifts as dangerous and rely on real-time sensing.",
            "steps": [
                "1. Note the emphasis on rapid change.",
                "2. Identify response: continuous monitoring.",
                "3. Eliminate options suggesting stability or delay.",
            ],
            "fastStrategy": "Volatile conditions require constant checks.",
        },
        {
            "question": "Why does the passage pair technology with human judgment?",
            "choices": {
                "A": "Sensors replace terrain reading",
                "B": "Data can mislead without field context",
                "C": "Humans cannot read wind",
                "D": "Satellites are too slow",
            },
            "answer": "B",
            "explanation": "Crews still evaluate terrain and escape routes; tech is supportive, not sufficient.",
            "steps": [
                "1. Find statements about tech limits.",
                "2. Note need for terrain/escape assessment.",
                "3. Choose the option showing complementary roles.",
            ],
            "fastStrategy": "Look for balance/limits language.",
        },
        {
            "question": "Which factor could most suddenly reverse crew safety?",
            "choices": {
                "A": "Slight wind shift",
                "B": "Fuel truck delay",
                "C": "Radio check",
                "D": "Nightfall",
            },
            "answer": "A",
            "explanation": "Small changes in wind/humidity/temperature can turn situations dangerous quickly.",
            "steps": [
                "1. Locate risks listed.",
                "2. Identify which are rapid triggers.",
                "3. Select the factor named as fast-changing.",
            ],
            "fastStrategy": "Use the text’s specific risk examples.",
        },
        {
            "question": "What implicit risk does the passage highlight about committing to a position?",
            "choices": {
                "A": "Crews forget exits",
                "B": "Escape routes can close if not preplanned",
                "C": "Satellites fail at night",
                "D": "Sensors drain batteries",
            },
            "answer": "B",
            "explanation": "They evaluate escape routes before committing because conditions can trap crews.",
            "steps": [
                "1. Note the sequencing: assess terrain/escape before committing.",
                "2. Infer the danger of blocked exits.",
                "3. Pick the consequence implied.",
            ],
            "fastStrategy": "When preplanning is stressed, think what happens without it.",
        },
        {
            "question": "Which title best captures the passage’s message?",
            "choices": {
                "A": "Humidity Alone Predicts Wildfires",
                "B": "Set-and-Forget Fire Plans",
                "C": "Real-Time Wildfire Decisions: Tech Plus Judgment",
                "D": "Why Structural Fires Are Riskier",
            },
            "answer": "C",
            "explanation": "Title reflects volatility and the combined use of sensing and human calls.",
            "steps": [
                "1. Extract main theme: rapid change + combined tools.",
                "2. Remove narrow or off-target titles.",
                "3. Choose the one summarizing both elements.",
            ],
            "fastStrategy": "Main idea = volatility + blended decision-making.",
        },
    ],
    2: [
        {
            "question": "What core advantage makes drones valuable in disasters?",
            "choices": {
                "A": "Unlimited payload",
                "B": "Bypass destroyed ground routes quickly",
                "C": "Cheaper than all vehicles",
                "D": "Require no planning",
            },
            "answer": "B",
            "explanation": "They fly over blocked infrastructure to reach cut-off areas fast.",
            "steps": [
                "1. Find described advantage.",
                "2. Note payload is limited.",
                "3. Pick bypass/rapid access.",
            ],
            "fastStrategy": "Match advantage explicitly stated.",
        },
        {
            "question": "What constraint shapes how drones are deployed?",
            "choices": {
                "A": "They cannot fly in rain",
                "B": "They carry small loads so many flights are needed",
                "C": "They need airports",
                "D": "They only map terrain",
            },
            "answer": "B",
            "explanation": "Small payloads mean multiple quick sorties compensate.",
            "steps": [
                "1. Identify stated limitation.",
                "2. Link to operational pattern (many units).",
                "3. Choose matching option.",
            ],
            "fastStrategy": "Limitation → operational workaround.",
        },
        {
            "question": "What does their inclusion in early protocols imply?",
            "choices": {
                "A": "They are experimental only",
                "B": "They are now considered essential first-wave assets",
                "C": "They replace all trucks",
                "D": "They wait for roads to reopen",
            },
            "answer": "B",
            "explanation": "Planners integrate them at the start, showing core role.",
            "steps": [
                "1. Note timing: early response.",
                "2. Infer status: standard tool.",
                "3. Reject extremes (replace everything).",
            ],
            "fastStrategy": "Early-phase inclusion = essential.",
        },
        {
            "question": "Which outcome is directly supported?",
            "choices": {
                "A": "Heavier loads than trucks",
                "B": "Slower than walking",
                "C": "Faster relief despite small cargo",
                "D": "Less reliable than blocked roads",
            },
            "answer": "C",
            "explanation": "Speed and numbers offset small cargo, improving relief timing.",
            "steps": [
                "1. Link speed + multiplicity to outcome.",
                "2. Remove claims contradicting text.",
                "3. Choose supported outcome.",
            ],
            "fastStrategy": "Look for the tradeoff resolved in text.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Heavy Lift Drones Only",
                "B": "Rapid Aerial Lifelines in Disasters",
                "C": "Why Roads Beat Drones",
                "D": "Tourism Uses of Drones",
            },
            "answer": "B",
            "explanation": "Captures speed to cut-off areas with small loads.",
            "steps": [
                "1. Main idea: rapid relief over damaged routes.",
                "2. Remove off-scope options.",
                "3. Pick concise fit.",
            ],
            "fastStrategy": "Title mirrors main benefit and context.",
        },
    ],
    3: [
        {
            "question": "Why are naps capped at ~20 minutes?",
            "choices": {
                "A": "Long naps stop REM",
                "B": "To avoid sleep inertia that follows deeper sleep",
                "C": "Short naps are fashionable",
                "D": "Companies ban longer rest",
            },
            "answer": "B",
            "explanation": "Brief naps prevent grogginess from deeper stages.",
            "steps": [
                "1. Identify risk of long naps.",
                "2. Connect to cap rationale.",
                "3. Choose option naming sleep inertia.",
            ],
            "fastStrategy": "Use stated physiological reason.",
        },
        {
            "question": "What business logic supports nap policies?",
            "choices": {
                "A": "Lower rent",
                "B": "Productivity and fewer errors outweigh the break time",
                "C": "Legal compliance",
                "D": "Eliminate night shifts",
            },
            "answer": "B",
            "explanation": "Firms see fewer mistakes and better recovery improving net output.",
            "steps": [
                "1. Find stated benefits.",
                "2. Weigh vs time cost.",
                "3. Pick productivity-over-time rationale.",
            ],
            "fastStrategy": "Cost-benefit stated in passage.",
        },
        {
            "question": "What inference counters critics who fear lost output?",
            "choices": {
                "A": "Studies show overall efficiency rises",
                "B": "Naps end workdays",
                "C": "Critics lack data",
                "D": "Naps replace sleep",
            },
            "answer": "A",
            "explanation": "Evidence shows performance gains offset break length.",
            "steps": [
                "1. Note critics’ concern.",
                "2. Identify passage evidence.",
                "3. Choose evidence-based rebuttal.",
            ],
            "fastStrategy": "Use passage data to rebut claim.",
        },
        {
            "question": "Which aspect is most central to the passage’s claim?",
            "choices": {
                "A": "Caffeine pricing",
                "B": "Optimal nap duration and benefits",
                "C": "Weekend sleep patterns",
                "D": "Office lighting",
            },
            "answer": "B",
            "explanation": "Focus is on short nap duration and cognitive benefits at work.",
            "steps": [
                "1. Extract main theme.",
                "2. Remove unrelated factors.",
                "3. Select core focus.",
            ],
            "fastStrategy": "Ask: what is the passage mostly about?",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Eliminating Overnight Shifts",
                "B": "Short Naps, Sharper Work",
                "C": "Why Sleep Is Harmful",
                "D": "The End of Office Chairs",
            },
            "answer": "B",
            "explanation": "Summarizes brief naps boosting performance.",
            "steps": [
                "1. Match to main claim.",
                "2. Remove unrelated/absurd options.",
                "3. Pick concise fit.",
            ],
            "fastStrategy": "Title = main claim shorthand.",
        },
    ],
    4: [
        {
            "question": "What tension drives the passage?",
            "choices": {
                "A": "Green spaces vs. recreation",
                "B": "Health and environmental benefits vs. development pressure",
                "C": "Parks vs. agriculture",
                "D": "Trees vs. transit",
            },
            "answer": "B",
            "explanation": "It contrasts benefits with competition from commercial development.",
            "steps": [
                "1. Identify two forces described.",
                "2. Note competition for land.",
                "3. Select option reflecting that tension.",
            ],
            "fastStrategy": "Look for paired contrasts.",
        },
        {
            "question": "Which benefit is explicitly cited?",
            "choices": {
                "A": "Higher rents",
                "B": "Cooling during heat waves",
                "C": "More car traffic",
                "D": "Guaranteed housing",
            },
            "answer": "B",
            "explanation": "Cooling effect is listed among benefits.",
            "steps": [
                "1. Recall listed benefits.",
                "2. Pick the stated one.",
                "3. Discard unstated outcomes.",
            ],
            "fastStrategy": "Detail question: match wording.",
        },
        {
            "question": "What do rooftop gardens and vertical forests signal?",
            "choices": {
                "A": "Cities abandon greenery",
                "B": "Creative integration of nature in dense areas",
                "C": "Preference for private parks",
                "D": "Inevitable loss of trees",
            },
            "answer": "B",
            "explanation": "They show innovative ways to add nature with limited land.",
            "steps": [
                "1. Note examples given.",
                "2. Infer purpose: integrate despite constraints.",
                "3. Choose aligned option.",
            ],
            "fastStrategy": "Use examples as evidence.",
        },
        {
            "question": "What purpose does the health research serve?",
            "choices": {
                "A": "Oppose parks",
                "B": "Justify protecting/expanding green spaces",
                "C": "Promote shopping malls",
                "D": "Limit outdoor exercise",
            },
            "answer": "B",
            "explanation": "Health evidence supports defending green space amid pressure.",
            "steps": [
                "1. See how evidence is used.",
                "2. Connect to argument for preservation.",
                "3. Pick matching purpose.",
            ],
            "fastStrategy": "Evidence usually backs the main argument.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Nature’s Edge in Crowded Cities",
                "B": "Parking Lots vs. Parks",
                "C": "The Cost of Roofs",
                "D": "Abandoning Urban Trees",
            },
            "answer": "A",
            "explanation": "Title captures benefit + constraint story.",
            "steps": [
                "1. Summarize passage.",
                "2. Remove narrow/off options.",
                "3. Pick concise fit.",
            ],
            "fastStrategy": "Title mirrors central tension.",
        },
    ],
    5: [
        {
            "question": "Which factor directly fuels the rise in blooms?",
            "choices": {
                "A": "Reduced nutrients",
                "B": "Nutrient runoff plus warmer waters",
                "C": "Less rainfall",
                "D": "Fewer coastal cities",
            },
            "answer": "B",
            "explanation": "Runoff rich in N/P and warmer temps drive blooms.",
            "steps": [
                "1. Find causal factors listed.",
                "2. Combine as stated.",
                "3. Select matching option.",
            ],
            "fastStrategy": "Use explicit causal list.",
        },
        {
            "question": "What is the purpose of early-warning models?",
            "choices": {
                "A": "Promote tourism",
                "B": "Predict blooms early to limit damage",
                "C": "Ban fertilizers",
                "D": "Raise ocean temps",
            },
            "answer": "B",
            "explanation": "They forecast blooms before widespread spread.",
            "steps": [
                "1. Identify model goal.",
                "2. Remove unrelated aims.",
                "3. Pick prevention/mitigation.",
            ],
            "fastStrategy": "Purpose question: why built?",
        },
        {
            "question": "Which consequence is highlighted?",
            "choices": {
                "A": "Better shellfish flavor",
                "B": "Fish die-offs and contaminated shellfish",
                "C": "Coral recovery",
                "D": "Increased tourism",
            },
            "answer": "B",
            "explanation": "Passage lists die-offs and contamination impacts.",
            "steps": [
                "1. Recall impacts stated.",
                "2. Pick exact match.",
                "3. Reject unstated outcomes.",
            ],
            "fastStrategy": "Detail match.",
        },
        {
            "question": "What broader risk do blooms pose to coastal economies?",
            "choices": {
                "A": "Permanent cooling",
                "B": "Temporary shutdowns of fishing/tourism",
                "C": "Unlimited fertilizer sales",
                "D": "Cheaper seafood",
            },
            "answer": "B",
            "explanation": "Closures of coastal industries like fishing/tourism are mentioned.",
            "steps": [
                "1. Find economic effects.",
                "2. Select shutdown/closure effect.",
                "3. Remove opposites.",
            ],
            "fastStrategy": "Look for economic impact statements.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Rising Red Tides and Runoff",
                "B": "The End of Coastlines",
                "C": "Coral Reefs Recover",
                "D": "Permanent Ocean Cooling",
            },
            "answer": "A",
            "explanation": "Summarizes increasing blooms tied to runoff.",
            "steps": [
                "1. Summarize core trend.",
                "2. Remove unrelated.",
                "3. Choose concise match.",
            ],
            "fastStrategy": "Title = main trend.",
        },
    ],
    6: [
        {
            "question": "What core benefit do adaptive signals provide?",
            "choices": {
                "A": "Fixed timing",
                "B": "Real-time timing that cuts idling and improves flow",
                "C": "Removal of sensors",
                "D": "Higher speed limits",
            },
            "answer": "B",
            "explanation": "They adjust to flow, reducing idling and improving travel times.",
            "steps": [
                "1. Note described benefit.",
                "2. Match to option.",
                "3. Exclude unrelated claims.",
            ],
            "fastStrategy": "Use stated benefit.",
        },
        {
            "question": "Which barrier slows adoption?",
            "choices": {
                "A": "Too many pedestrians",
                "B": "Need for infrastructure upgrades and budgets",
                "C": "Ban on data",
                "D": "Lack of interest",
            },
            "answer": "B",
            "explanation": "Passage cites upgrade costs and budgets.",
            "steps": [
                "1. Identify cited barriers.",
                "2. Choose matching option.",
                "3. Remove unstated ones.",
            ],
            "fastStrategy": "Barrier = cost/infra.",
        },
        {
            "question": "What does engineer optimism imply?",
            "choices": {
                "A": "Costs likely fall with better sensors",
                "B": "Traffic is unsolvable",
                "C": "Fixed timers will return",
                "D": "Data processing will slow",
            },
            "answer": "A",
            "explanation": "They expect tech advances to ease adoption.",
            "steps": [
                "1. Note optimism stated.",
                "2. Infer reason: improving tech/cost.",
                "3. Pick aligned option.",
            ],
            "fastStrategy": "Optimism usually tied to tech/cost trends.",
        },
        {
            "question": "Which outcome is directly mentioned?",
            "choices": {
                "A": "Eliminating signals",
                "B": "Reducing fuel use via less idling",
                "C": "Doubling fares",
                "D": "Banning buses",
            },
            "answer": "B",
            "explanation": "Reduced idling lowers fuel use; explicitly noted.",
            "steps": [
                "1. Recall listed outcomes.",
                "2. Choose matching one.",
                "3. Remove others.",
            ],
            "fastStrategy": "Detail match.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Signals that Listen to Traffic",
                "B": "Why Sensors Are Obsolete",
                "C": "Manual Policing at Intersections",
                "D": "Banning Pedestrians",
            },
            "answer": "A",
            "explanation": "Captures adaptive, data-driven timing theme.",
            "steps": [
                "1. Summarize core idea.",
                "2. Remove irrelevant titles.",
                "3. Choose concise fit.",
            ],
            "fastStrategy": "Title reflects real-time adaptation.",
        },
    ],
    7: [
        {
            "question": "What do inland coastal artifacts suggest about prehistoric groups?",
            "choices": {
                "A": "They stayed isolated",
                "B": "They traded across long distances",
                "C": "They avoided symbolism",
                "D": "They migrated yearly",
            },
            "answer": "B",
            "explanation": "Coastal items far inland imply exchange networks.",
            "steps": [
                "1. Link evidence (coastal items inland).",
                "2. Infer trade networks.",
                "3. Choose matching option.",
            ],
            "fastStrategy": "Evidence → inference.",
        },
        {
            "question": "Which evidence best supports early trade?",
            "choices": {
                "A": "Shells/minerals hundreds of miles inland",
                "B": "Written ledgers",
                "C": "Coins",
                "D": "Horses",
            },
            "answer": "A",
            "explanation": "Passage cites coastal-origin items inland.",
            "steps": [
                "1. Recall stated evidence.",
                "2. Pick exact support.",
                "3. Exclude unstated artifacts.",
            ],
            "fastStrategy": "Detail match.",
        },
        {
            "question": "What social inference follows from exchanging symbolic items?",
            "choices": {
                "A": "Purely functional trade",
                "B": "Shared rituals or status markers existed",
                "C": "No cooperation",
                "D": "Only coastal dominance",
            },
            "answer": "B",
            "explanation": "Symbolic items suggest ritual/status uses, implying social links.",
            "steps": [
                "1. Note mention of pigments/shells.",
                "2. Infer cultural exchange.",
                "3. Choose aligned option.",
            ],
            "fastStrategy": "Symbolic goods → social meaning.",
        },
        {
            "question": "Why does this finding shift prior assumptions?",
            "choices": {
                "A": "Shows isolation began later",
                "B": "Reveals cooperation before formal civilizations",
                "C": "Proves cities existed",
                "D": "Invalidates archaeology",
            },
            "answer": "B",
            "explanation": "Trade indicates cooperation earlier than assumed.",
            "steps": [
                "1. Identify old assumption (isolation).",
                "2. New evidence (trade).",
                "3. Choose inference about earlier cooperation.",
            ],
            "fastStrategy": "Contrast old vs new view.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Isolation of Early Villages",
                "B": "Ancient Networks Across Distance",
                "C": "Decline of Coastlines",
                "D": "The Invention of Writing",
            },
            "answer": "B",
            "explanation": "Title reflects early long-distance exchange.",
            "steps": [
                "1. Summarize discovery.",
                "2. Remove mismatches.",
                "3. Select concise fit.",
            ],
            "fastStrategy": "Title = finding.",
        },
    ],
    8: [
        {
            "question": "What physiological effect does microgravity produce?",
            "choices": {
                "A": "Fluid shifts upward increasing eye pressure",
                "B": "More muscle growth",
                "C": "Lower blood flow to head",
                "D": "Improved vision",
            },
            "answer": "A",
            "explanation": "Fluid moves toward head, affecting eyes.",
            "steps": [
                "1. Note described effect.",
                "2. Pick matching option.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "Why are countermeasures under study?",
            "choices": {
                "A": "Missions are shortening",
                "B": "Vision issues threaten longer Moon/Mars flights",
                "C": "Robots need them",
                "D": "Gravity increases in space",
            },
            "answer": "B",
            "explanation": "Longer missions need eye health solutions.",
            "steps": [
                "1. Link vision issues to future missions.",
                "2. Infer need for fixes.",
                "3. Choose aligned option.",
            ],
            "fastStrategy": "Future missions drive mitigation.",
        },
        {
            "question": "What does ongoing research imply about current solutions?",
            "choices": {
                "A": "They are incomplete",
                "B": "They are perfect",
                "C": "They are irrelevant",
                "D": "They worsen vision",
            },
            "answer": "A",
            "explanation": "Researchers caution continued study—solutions not final.",
            "steps": [
                "1. Note call for continued research.",
                "2. Infer current gaps.",
                "3. Choose matching option.",
            ],
            "fastStrategy": "More research = not done.",
        },
        {
            "question": "Which countermeasure is mentioned?",
            "choices": {
                "A": "Gravity boots",
                "B": "Compression garments",
                "C": "Laser eye surgery in orbit",
                "D": "Sleeping upright",
            },
            "answer": "B",
            "explanation": "Compression garments noted to manage fluid shift.",
            "steps": [
                "1. Recall listed measures.",
                "2. Pick exact one.",
                "3. Exclude unstated.",
            ],
            "fastStrategy": "Detail match.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Microgravity and the Eyes",
                "B": "Why Space Cures Vision",
                "C": "Abandoning Manned Spaceflight",
                "D": "No Need for Research",
            },
            "answer": "A",
            "explanation": "Captures fluid shifts and vision concern.",
            "steps": [
                "1. Summarize passage.",
                "2. Remove mismatches.",
                "3. Choose concise fit.",
            ],
            "fastStrategy": "Title = main focus.",
        },
    ],
    9: [
        {
            "question": "What trend does the passage highlight?",
            "choices": {
                "A": "More disposable buying",
                "B": "Growing repair culture driven by cost and sustainability",
                "C": "End of recycling",
                "D": "Cheaper raw materials",
            },
            "answer": "B",
            "explanation": "Repairs rising due to costs, DIY parts, environmental concerns.",
            "steps": [
                "1. Identify described shift.",
                "2. Pick matching option.",
                "3. Exclude opposite claims.",
            ],
            "fastStrategy": "Main trend match.",
        },
        {
            "question": "Which factor enables DIY repairs?",
            "choices": {
                "A": "Fewer tutorials",
                "B": "Accessible guides and parts",
                "C": "Ban on replacements",
                "D": "Cheaper new goods",
            },
            "answer": "B",
            "explanation": "Tutorials/parts make repairs doable.",
            "steps": [
                "1. Recall enabling factors.",
                "2. Choose stated one.",
                "3. Exclude inverses.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "Why might manufacturers hesitate to build for longevity?",
            "choices": {
                "A": "Fear reduced replacement sales",
                "B": "Legal bans",
                "C": "Lack of materials",
                "D": "Higher demand",
            },
            "answer": "A",
            "explanation": "They worry durable designs cut short-term sales.",
            "steps": [
                "1. Find manufacturer concern.",
                "2. Infer sales impact.",
                "3. Choose matching option.",
            ],
            "fastStrategy": "Use stated hesitation reason.",
        },
        {
            "question": "What future does the passage project?",
            "choices": {
                "A": "Repair culture fading",
                "B": "Landfill growth",
                "C": "Repair-oriented consumption expanding with sustainability focus",
                "D": "Parts disappearing",
            },
            "answer": "C",
            "explanation": "Economists expect repair trend to continue as sustainability matters more.",
            "steps": [
                "1. Note forecast.",
                "2. Pick aligned option.",
                "3. Exclude contrary outcomes.",
            ],
            "fastStrategy": "Match stated projection.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Repairs Rising with Sustainability",
                "B": "End of DIY",
                "C": "Cheap Goods Forever",
                "D": "Waste Without Limits",
            },
            "answer": "A",
            "explanation": "Summarizes the repair trend and sustainability driver.",
            "steps": [
                "1. Summarize passage.",
                "2. Remove mismatches.",
                "3. Select fit.",
            ],
            "fastStrategy": "Title = trend + driver.",
        },
    ],
    10: [
        {
            "question": "What distinguishes predictive analytics in planning?",
            "choices": {
                "A": "Ignores live data",
                "B": "Uses live feeds to forecast and test scenarios",
                "C": "Removes transit",
                "D": "Relies on guesswork",
            },
            "answer": "B",
            "explanation": "It incorporates live sensor/app data to forecast and simulate changes.",
            "steps": [
                "1. Identify defining feature.",
                "2. Pick matching option.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Define the tool per text.",
        },
        {
            "question": "Why is data quality critical?",
            "choices": {
                "A": "Models ignore inputs",
                "B": "Bad inputs yield flawed predictions that can worsen congestion",
                "C": "It speeds coding",
                "D": "It sets speed limits",
            },
            "answer": "B",
            "explanation": "Poor data can produce wrong forecasts, harming traffic.",
            "steps": [
                "1. Note caution about input quality.",
                "2. Connect to risk.",
                "3. Choose matching option.",
            ],
            "fastStrategy": "Garbage in → garbage out.",
        },
        {
            "question": "Which advantage is noted?",
            "choices": {
                "A": "No sensors needed",
                "B": "Testing scenarios before physical changes",
                "C": "Guaranteed no congestion",
                "D": "Replacing planners",
            },
            "answer": "B",
            "explanation": "Models trial impacts virtually to cut cost/risk.",
            "steps": [
                "1. Recall cited advantage.",
                "2. Pick exact match.",
                "3. Exclude exaggerations.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "What risk follows from inaccurate inputs?",
            "choices": {
                "A": "Instant subway expansion",
                "B": "Flawed forecasts that may worsen traffic",
                "C": "Free parking",
                "D": "Better safety",
            },
            "answer": "B",
            "explanation": "Text warns bad data can make predictions wrong, harming flow.",
            "steps": [
                "1. Identify risk.",
                "2. Connect to output quality.",
                "3. Choose aligned option.",
            ],
            "fastStrategy": "Risk = bad outputs.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Forecasting Traffic with Live Data",
                "B": "Eliminating Transit",
                "C": "Historic Maps Only",
                "D": "Why Sensors Fail",
            },
            "answer": "A",
            "explanation": "Captures live-data forecasting and scenario testing.",
            "steps": [
                "1. Summarize passage.",
                "2. Remove mismatches.",
                "3. Select fit.",
            ],
            "fastStrategy": "Title = defining approach.",
        },
    ],
    11: [
        {
            "question": "What strategy does the passage endorse for coastal protection?",
            "choices": {
                "A": "Single tall seawalls",
                "B": "Layered defenses combining engineered and natural elements",
                "C": "No defenses",
                "D": "Only wetlands",
            },
            "answer": "B",
            "explanation": "It highlights hybrid approaches with seawalls plus living shorelines.",
            "steps": [
                "1. Note described approach.",
                "2. Select combined strategy.",
                "3. Exclude extremes.",
            ],
            "fastStrategy": "Hybrid is key.",
        },
        {
            "question": "Which benefit of living shorelines is mentioned?",
            "choices": {
                "A": "Increase erosion",
                "B": "Absorb wave energy and aid ecology",
                "C": "Eliminate planning",
                "D": "Work only in deserts",
            },
            "answer": "B",
            "explanation": "They reduce erosion and support ecosystems.",
            "steps": [
                "1. Recall benefit.",
                "2. Pick exact match.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "What limitation is acknowledged?",
            "choices": {
                "A": "Unsuitable in high-energy or space-limited coasts",
                "B": "Always free",
                "C": "Ban natural features",
                "D": "Need no coordination",
            },
            "answer": "A",
            "explanation": "High wave energy or limited space can make them impractical.",
            "steps": [
                "1. Find stated limits.",
                "2. Choose matching option.",
                "3. Exclude unstated claims.",
            ],
            "fastStrategy": "Use explicit caveats.",
        },
        {
            "question": "What does the shift to layered defenses imply?",
            "choices": {
                "A": "Rigid barriers are being supplemented",
                "B": "Sea-level rise ended",
                "C": "Natural defenses banned",
                "D": "Only walls remain",
            },
            "answer": "A",
            "explanation": "Cities move from one-size seawalls to adaptable mixes.",
            "steps": [
                "1. Identify implication of hybrid approach.",
                "2. Pick option showing supplementation.",
                "3. Exclude contradictions.",
            ],
            "fastStrategy": "Hybrid → supplement, not abandon.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Hybrid Defenses for Rising Seas",
                "B": "Abandoning Coasts",
                "C": "Why Wetlands Cause Floods",
                "D": "Single Walls Win",
            },
            "answer": "A",
            "explanation": "Title reflects layered engineered + natural defenses.",
            "steps": [
                "1. Summarize focus.",
                "2. Remove off-target titles.",
                "3. Pick fit.",
            ],
            "fastStrategy": "Title mirrors strategy.",
        },
    ],
    12: [
        {
            "question": "What dual challenge does advanced recycling address?",
            "choices": {
                "A": "Flooding and storms",
                "B": "Water scarcity plus public hesitation",
                "C": "Agricultural yields",
                "D": "Traffic",
            },
            "answer": "B",
            "explanation": "Tech solves scarcity but faces acceptance barriers.",
            "steps": [
                "1. Identify two issues: scarcity + acceptance.",
                "2. Pick option with both.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Note paired problem/solution.",
        },
        {
            "question": "Which treatment stages are listed?",
            "choices": {
                "A": "Boiling only",
                "B": "Membranes, UV, activated carbon",
                "C": "Evaporation",
                "D": "Freezing",
            },
            "answer": "B",
            "explanation": "These three stages are named.",
            "steps": [
                "1. Recall stages.",
                "2. Choose exact set.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "Why focus outreach on perception?",
            "choices": {
                "A": "Tech unsafe",
                "B": "Residents hesitate despite safety evidence",
                "C": "Filters unavailable",
                "D": "Laws require it",
            },
            "answer": "B",
            "explanation": "Hesitation persists even with safety data; outreach aims to build trust.",
            "steps": [
                "1. Identify barrier: perception.",
                "2. Connect to outreach goal.",
                "3. Choose matching option.",
            ],
            "fastStrategy": "Barrier → outreach.",
        },
        {
            "question": "Why suit urban settings?",
            "choices": {
                "A": "Unlimited reservoirs",
                "B": "Systems fit where reservoirs cannot expand",
                "C": "Need more fertilizer",
                "D": "Ban on imports",
            },
            "answer": "B",
            "explanation": "Compact systems work where new reservoirs are impossible.",
            "steps": [
                "1. Note stated advantage.",
                "2. Pick aligned option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Use explicit rationale.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Winning Trust in Water Recycling",
                "B": "Reservoirs Forever",
                "C": "Abandoning Filtration",
                "D": "Why Water Is Endless",
            },
            "answer": "A",
            "explanation": "Reflects technology plus acceptance hurdle.",
            "steps": [
                "1. Summarize theme.",
                "2. Remove mismatches.",
                "3. Choose fit.",
            ],
            "fastStrategy": "Title = tech + trust.",
        },
    ],
    13: [
        {
            "question": "What shift in battery R&D is described?",
            "choices": {
                "A": "More lithium mining only",
                "B": "Exploring abundant sodium and better recycling",
                "C": "Ending electric vehicles",
                "D": "Dropping metal use",
            },
            "answer": "B",
            "explanation": "Passage highlights sodium and recycling for sustainability.",
            "steps": [
                "1. Identify new directions.",
                "2. Pick matching option.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Main shift match.",
        },
        {
            "question": "What trade-off do sodium batteries face?",
            "choices": {
                "A": "Higher energy density",
                "B": "Lower energy density but cheaper materials",
                "C": "Require rare metals",
                "D": "Non-rechargeable",
            },
            "answer": "B",
            "explanation": "They are cheaper/abundant but store less per size.",
            "steps": [
                "1. Note pros/cons.",
                "2. Pick combined trade-off.",
                "3. Exclude mismatches.",
            ],
            "fastStrategy": "Include both sides.",
        },
        {
            "question": "What role does recycling play?",
            "choices": {
                "A": "Increase mining",
                "B": "Recover metals to cut new extraction",
                "C": "Prevent reuse",
                "D": "Only for sodium",
            },
            "answer": "B",
            "explanation": "Recycling recovers valuable metals, reducing mining.",
            "steps": [
                "1. Find recycling purpose.",
                "2. Pick aligned option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Purpose match.",
        },
        {
            "question": "Which applications suit sodium cells per passage?",
            "choices": {
                "A": "Where top energy density isn’t critical",
                "B": "All long-range EVs now",
                "C": "Only grid storage",
                "D": "No current uses",
            },
            "answer": "A",
            "explanation": "Lower density fits shorter-range/less demanding uses.",
            "steps": [
                "1. Note limitation (density).",
                "2. Infer suitable cases.",
                "3. Pick aligned option.",
            ],
            "fastStrategy": "Use limitation to pick fit.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Greener Batteries: Sodium and Recycling",
                "B": "End of Electricity",
                "C": "Gasoline Forever",
                "D": "Mining Without Metals",
            },
            "answer": "A",
            "explanation": "Captures sustainable materials plus recycling focus.",
            "steps": [
                "1. Summarize shift.",
                "2. Remove mismatches.",
                "3. Pick fit.",
            ],
            "fastStrategy": "Title = sustainability focus.",
        },
    ],
    14: [
        {
            "question": "What makes acoustic monitoring powerful?",
            "choices": {
                "A": "No data to review",
                "B": "Continuous recordings plus ML to detect patterns",
                "C": "It replaces all fieldwork instantly",
                "D": "Only captures silence",
            },
            "answer": "B",
            "explanation": "Continuous audio with ML helps reveal migration/breeding despite noise.",
            "steps": [
                "1. Identify key combo: continuous + ML.",
                "2. Pick matching option.",
                "3. Exclude extremes.",
            ],
            "fastStrategy": "Combine two main tools.",
        },
        {
            "question": "What challenge complicates analysis?",
            "choices": {
                "A": "No animal sounds",
                "B": "Background noise obscures signals",
                "C": "Lack of storage",
                "D": "No devices",
            },
            "answer": "B",
            "explanation": "Wind/river noise interferes with clarity.",
            "steps": [
                "1. Recall obstacle.",
                "2. Pick matching option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "What does ML adoption imply?",
            "choices": {
                "A": "Manual review time can drop even if models imperfect",
                "B": "No need to record",
                "C": "Noise eliminated",
                "D": "Data unused",
            },
            "answer": "A",
            "explanation": "ML aids ID, reducing review effort though not flawless.",
            "steps": [
                "1. Note stated effect.",
                "2. Pick aligned option.",
                "3. Exclude exaggerations.",
            ],
            "fastStrategy": "Imperfect aid still helpful.",
        },
        {
            "question": "What insight can recordings reveal?",
            "choices": {
                "A": "Migration and breeding patterns",
                "B": "Stock prices",
                "C": "Tax records",
                "D": "Planetary orbits",
            },
            "answer": "A",
            "explanation": "Passage cites migration/breeding/habitat use patterns.",
            "steps": [
                "1. Recall insights listed.",
                "2. Pick matching option.",
                "3. Exclude unrelated.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Listening Smartly to Wildlife",
                "B": "Silent Forests",
                "C": "Noise Ends Ecology",
                "D": "Why Sound Fails",
            },
            "answer": "A",
            "explanation": "Title captures acoustic + ML approach.",
            "steps": [
                "1. Summarize main approach.",
                "2. Remove off options.",
                "3. Choose fit.",
            ],
            "fastStrategy": "Title = approach.",
        },
    ],
    15: [
        {
            "question": "What grid role do battery farms serve?",
            "choices": {
                "A": "Eliminate renewables",
                "B": "Store surplus and release during peaks",
                "C": "Replace transmission",
                "D": "Raise fossil use",
            },
            "answer": "B",
            "explanation": "They absorb excess and deliver when demand rises.",
            "steps": [
                "1. Identify described role.",
                "2. Pick matching option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Role = buffer.",
        },
        {
            "question": "Which risk is mentioned?",
            "choices": {
                "A": "Overheating if unmanaged",
                "B": "Too cold",
                "C": "No cost",
                "D": "Instant payback",
            },
            "answer": "A",
            "explanation": "Overheating in large banks is flagged.",
            "steps": [
                "1. Recall risk.",
                "2. Choose matching option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "What do new chemistries aim to improve?",
            "choices": {
                "A": "Risk",
                "B": "Safety at scale",
                "C": "Eliminate storage need",
                "D": "Stop renewables",
            },
            "answer": "B",
            "explanation": "Designed for safer large-scale operation.",
            "steps": [
                "1. Note goal.",
                "2. Pick matching option.",
                "3. Exclude mismatches.",
            ],
            "fastStrategy": "Goal = safer scaling.",
        },
        {
            "question": "Which benefit is explicit?",
            "choices": {
                "A": "Unlimited free power",
                "B": "Stabilizing grid by shifting energy",
                "C": "Ending grid demand",
                "D": "Removing space needs",
            },
            "answer": "B",
            "explanation": "Storing surplus then releasing stabilizes grid.",
            "steps": [
                "1. Recall benefit.",
                "2. Choose matching option.",
                "3. Exclude exaggerations.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Grid Batteries: Balancing Surplus and Demand",
                "B": "Why Renewables Fail",
                "C": "Free Power Forever",
                "D": "No More Safety",
            },
            "answer": "A",
            "explanation": "Captures balancing role and challenges.",
            "steps": [
                "1. Summarize passage.",
                "2. Remove off options.",
                "3. Pick fit.",
            ],
            "fastStrategy": "Title = role + challenge.",
        },
    ],
    16: [
        {
            "question": "What advantage does noninvasive imaging provide?",
            "choices": {
                "A": "Destroys artifacts",
                "B": "Maps buried features without excavation damage",
                "C": "Replaces analysis",
                "D": "Guarantees treasure",
            },
            "answer": "B",
            "explanation": "Radar/lidar reveal structures while preserving sites.",
            "steps": [
                "1. Identify advantage.",
                "2. Pick matching option.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Benefit = preserve + reveal.",
        },
        {
            "question": "What happens when radar and lidar combine?",
            "choices": {
                "A": "Instant fossils",
                "B": "Detailed 3D settlement models",
                "C": "No surface data",
                "D": "Removes vegetation",
            },
            "answer": "B",
            "explanation": "They produce detailed models showing patterns.",
            "steps": [
                "1. Recall combined effect.",
                "2. Pick matching option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "What does cost/training imply about adoption?",
            "choices": {
                "A": "Will likely grow as access improves",
                "B": "Will vanish",
                "C": "Banned worldwide",
                "D": "Already universal",
            },
            "answer": "A",
            "explanation": "Though costly now, likely to expand as tools become accessible.",
            "steps": [
                "1. Note current hurdle.",
                "2. Infer future trend mentioned.",
                "3. Pick aligned option.",
            ],
            "fastStrategy": "Hurdle now, growth later.",
        },
        {
            "question": "Why is the method valuable at fragile sites?",
            "choices": {
                "A": "Allows digging faster",
                "B": "Avoids disturbance while revealing layout",
                "C": "Raises water",
                "D": "Removes need for permits",
            },
            "answer": "B",
            "explanation": "It preserves artifacts while mapping them.",
            "steps": [
                "1. Link noninvasive to preservation.",
                "2. Pick matching option.",
                "3. Exclude irrelevant.",
            ],
            "fastStrategy": "Noninvasive → preserve.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Seeing Ancient Cities Without a Shovel",
                "B": "Destroying History for Data",
                "C": "Why Mapping Fails",
                "D": "Fossils Overnight",
            },
            "answer": "A",
            "explanation": "Title captures noninvasive mapping theme.",
            "steps": [
                "1. Summarize approach.",
                "2. Remove off options.",
                "3. Pick fit.",
            ],
            "fastStrategy": "Title = noninvasive mapping.",
        },
    ],
    17: [
        {
            "question": "What is the main claim about precision farming?",
            "choices": {
                "A": "Data wastes resources",
                "B": "Data-driven inputs boost efficiency despite connectivity/cost hurdles",
                "C": "It ends irrigation",
                "D": "Only indoor use",
            },
            "answer": "B",
            "explanation": "Sensors/drones tailor inputs; barriers are cost/connectivity.",
            "steps": [
                "1. Identify benefits + hurdles.",
                "2. Pick option with both.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Include benefit + caveat.",
        },
        {
            "question": "How do drones assist?",
            "choices": {
                "A": "Harvest crops",
                "B": "Survey fields to spot stress early",
                "C": "Block sunlight",
                "D": "Replace sensors",
            },
            "answer": "B",
            "explanation": "They survey quickly and identify plant stress.",
            "steps": [
                "1. Recall drone role.",
                "2. Choose matching option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "What barrier is noted?",
            "choices": {
                "A": "Excess rain",
                "B": "Limited rural internet access",
                "C": "Too many sensors",
                "D": "Lack of sun",
            },
            "answer": "B",
            "explanation": "Connectivity limits adoption.",
            "steps": [
                "1. Identify hurdle.",
                "2. Pick matching option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Barrier recall.",
        },
        {
            "question": "What future is implied?",
            "choices": {
                "A": "Use will grow as tech becomes cheaper",
                "B": "It will disappear",
                "C": "It demands perfect weather",
                "D": "It is illegal",
            },
            "answer": "A",
            "explanation": "Passage expects wider use as cost/access improve.",
            "steps": [
                "1. Note forward-looking statement.",
                "2. Choose aligned option.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Future expectation noted.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Data and Drones for Smarter Fields",
                "B": "Farming Without Sensors",
                "C": "Abandoning Agriculture",
                "D": "Why Crops Don’t Need Water",
            },
            "answer": "A",
            "explanation": "Captures data-driven approach and tools.",
            "steps": [
                "1. Summarize theme.",
                "2. Remove off options.",
                "3. Pick fit.",
            ],
            "fastStrategy": "Title = data + drones.",
        },
    ],
    18: [
        {
            "question": "What core insight do vents offer about life?",
            "choices": {
                "A": "Life needs sunlight",
                "B": "Life can thrive via chemosynthesis in darkness",
                "C": "Oceans are sterile",
                "D": "Only shallow water matters",
            },
            "answer": "B",
            "explanation": "Vents host life without sunlight using chemosynthesis.",
            "steps": [
                "1. Identify main insight.",
                "2. Pick matching option.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Core novelty = no sunlight needed.",
        },
        {
            "question": "How do vent organisms get energy?",
            "choices": {
                "A": "Photosynthesis",
                "B": "Chemosynthesis from vent chemicals",
                "C": "Stored plants",
                "D": "Solar panels",
            },
            "answer": "B",
            "explanation": "Bacteria use chemical energy from vents.",
            "steps": [
                "1. Recall energy source.",
                "2. Pick matching option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "What obstacle limits research?",
            "choices": {
                "A": "Too shallow",
                "B": "Need costly submersibles",
                "C": "Lack of interest",
                "D": "Free access",
            },
            "answer": "B",
            "explanation": "Reaching vents requires advanced submersibles.",
            "steps": [
                "1. Identify hurdle.",
                "2. Choose matching option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Barrier recall.",
        },
        {
            "question": "What broader implication is drawn?",
            "choices": {
                "A": "Life elsewhere might exist in similar extreme settings",
                "B": "All planets need sun",
                "C": "Space oceans are impossible",
                "D": "Chemosynthesis is rare",
            },
            "answer": "A",
            "explanation": "If life thrives without sun, similar environments elsewhere could host life.",
            "steps": [
                "1. Note implication stated.",
                "2. Pick aligned option.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Use explicit inference to astrobiology.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Life in the Dark: Hydrothermal Lessons",
                "B": "Sunlit Beaches",
                "C": "Why Oceans Lack Life",
                "D": "Boiling Away Research",
            },
            "answer": "A",
            "explanation": "Captures unique dark ecosystems and significance.",
            "steps": [
                "1. Summarize focus.",
                "2. Remove off options.",
                "3. Choose fit.",
            ],
            "fastStrategy": "Title = unique ecosystem + insight.",
        },
    ],
    19: [
        {
            "question": "What health concern does chronic urban noise raise?",
            "choices": {
                "A": "Improved eyesight",
                "B": "Stress, sleep disruption, cardiovascular strain",
                "C": "Instant colds",
                "D": "Better metabolism",
            },
            "answer": "B",
            "explanation": "Passage ties chronic noise to stress, sleep issues, cardiovascular effects.",
            "steps": [
                "1. Recall listed effects.",
                "2. Pick matching option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "What do wearables reveal?",
            "choices": {
                "A": "Noise below limits",
                "B": "Exposures above limits day and night",
                "C": "Only daytime noise",
                "D": "Silence at night",
            },
            "answer": "B",
            "explanation": "Devices show many residents exceed recommended levels both day/night.",
            "steps": [
                "1. Recall measurement finding.",
                "2. Pick matching option.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "What do mitigation experiments imply?",
            "choices": {
                "A": "Total silence achievable",
                "B": "Cities accept permanent noise",
                "C": "Reducing intensity/duration is realistic even if silence isn’t",
                "D": "Noise must rise",
            },
            "answer": "C",
            "explanation": "Efforts aim to lessen noise, not eliminate it entirely.",
            "steps": [
                "1. Note mitigation goal.",
                "2. Infer implication.",
                "3. Pick aligned option.",
            ],
            "fastStrategy": "Mitigation ≠ elimination.",
        },
        {
            "question": "Which intervention is mentioned?",
            "choices": {
                "A": "Noise-amplifying pavement",
                "B": "Noise-reducing pavement and green space",
                "C": "24/7 sirens",
                "D": "No building codes",
            },
            "answer": "B",
            "explanation": "Cities test noise-reducing pavement, layouts, green spaces.",
            "steps": [
                "1. Recall interventions.",
                "2. Pick correct set.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "City Noise and Health: Finding Relief",
                "B": "Silencing the Suburbs",
                "C": "Why Noise Helps Sleep",
                "D": "Traffic Joy",
            },
            "answer": "A",
            "explanation": "Title reflects health impact and mitigation efforts.",
            "steps": [
                "1. Summarize passage.",
                "2. Remove off options.",
                "3. Pick fit.",
            ],
            "fastStrategy": "Title = impact + response.",
        },
    ],
    20: [
        {
            "question": "What advantage do new membranes offer?",
            "choices": {
                "A": "Weaker filtration",
                "B": "Durable, high-removal filtration in harsh wastewater",
                "C": "No pores",
                "D": "They add pollutants",
            },
            "answer": "B",
            "explanation": "Advanced polymers withstand harsh conditions and filter better.",
            "steps": [
                "1. Note stated advantage.",
                "2. Pick matching option.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Detail recall.",
        },
        {
            "question": "How do they work?",
            "choices": {
                "A": "Micropores trap contaminants while water passes",
                "B": "Boiling",
                "C": "Evaporation",
                "D": "Adding chemicals",
            },
            "answer": "A",
            "explanation": "Membranes use microscopic pores to filter.",
            "steps": [
                "1. Recall mechanism.",
                "2. Pick matching option.",
                "3. Exclude others.",
            ],
            "fastStrategy": "Mechanism recall.",
        },
        {
            "question": "What does charged-membrane design imply?",
            "choices": {
                "A": "Repels certain particles to boost performance",
                "B": "Stops water",
                "C": "Only filters salt",
                "D": "Reduces durability",
            },
            "answer": "A",
            "explanation": "Electrical charges help repel targeted particles.",
            "steps": [
                "1. Note feature.",
                "2. Infer function.",
                "3. Pick aligned option.",
            ],
            "fastStrategy": "Feature → function.",
        },
        {
            "question": "What future impact is suggested if trials succeed?",
            "choices": {
                "A": "No treatment needed",
                "B": "Factories abandon water",
                "C": "Better compliance with stricter regulations",
                "D": "Filters clog faster",
            },
            "answer": "C",
            "explanation": "Improved removal could help meet tighter rules.",
            "steps": [
                "1. Note potential outcome.",
                "2. Pick matching option.",
                "3. Exclude opposites.",
            ],
            "fastStrategy": "Outcome = better compliance.",
        },
        {
            "question": "Best title?",
            "choices": {
                "A": "Tough Membranes for Cleaner Wastewater",
                "B": "Filters that Fail",
                "C": "Pollution as Solution",
                "D": "No Need for Regulation",
            },
            "answer": "A",
            "explanation": "Captures durable membranes improving filtration.",
            "steps": [
                "1. Summarize passage.",
                "2. Remove mismatches.",
                "3. Pick fit.",
            ],
            "fastStrategy": "Title = durability + filtration.",
        },
    ],
}

for path in sorted(base_dir.glob('reading_comprehension_beginner_passage*.json')):
    num = int(re.search(r'passage(\d+)', path.name).group(1))
    with open(path) as f:
        data = json.load(f)
    passage = data['passage']
    passage_id = data.get('passageId', f'rc_b1_p{num:03d}')
    new_id = passage_id.replace('b1', 'e1', 1)
    out = base_dir / f'reading_comprehension_expert_passage{num}.json'
    questions = q[num]
    for idx, item in enumerate(questions, 1):
        item.setdefault('id', f'rc_e1_p{num:03d}_q{idx}')
    payload = {
        "subjectId": "reading_comprehension",
        "difficulty": "expert",
        "passageId": new_id,
        "passage": passage,
        "questions": questions,
    }
    with open(out, 'w') as f:
        json.dump(payload, f, indent=2)

print(f"Created {len(q)} expert passage files.")
